[mountpoint]
  path = "${SNAPMOUNT_MOUNTPOINT}"
  create = true

[[mounts]]
  type = "lvm"
  source = "/dev/arch_main/root"
  target = "/"
  [mounts.snapshot]
    lv_name = "root${SNAPMOUNT_LV_SUFFIX}"

[[mounts]]
  type = "lvm"
  source = "/dev/arch_main/home"
  target = "/home"
  [mounts.snapshot]
    lv_name = "home${SNAPMOUNT_LV_SUFFIX}"

[[mounts]]
  type = "bind"
  source = "/boot"

[[mounts]]
  type = "bind"
  source = "/boot/efi"

[[mounts]]
  type = "bind"
  writable = true
  source = "${RESTIC_CACHE_DIR}"
