name: Cloud storage

on:
  push:
    branches:
    - master

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: --no-track --locked --root cargo --path .
    - name: Extract branch name
      run: echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"
      id: extract_branch
    - uses: google-github-actions/upload-cloud-storage@main
      with:
        credentials: ${{ secrets.GCP_CREDENTIALS }}
        path: cargo/bin
        destination: ${{ secrets.GCS_BUCKET }}/${{ steps.extract_branch.outputs.branch }}
