name: Cloud storage

on:
  push:
    branches:
    - master

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: --no-track --locked --root .cargo --path .
    - uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    - uses: google-github-actions/setup-gcloud@v0.3.0
    - name: Publish build artifacts
      run: gsutil rsync -dr .cargo gs://${{ secrets.GCS_BUCKET }}/
